# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- dev*

pr:
- main

stages:
- stage: build
  displayName: Build Plugin
  jobs:
    - job: BuildPlugin
      strategy:
        matrix:
          mac:
            imageName: 'macOS-latest'
          windows:
            imageName: 'windows-latest'
          linux:
            imageName: 'ubuntu-latest'
      
      pool:
        vmImage: $(imageName)

      steps:
        - checkout: self
          fetchDepth: 1
          submodules: recursive
        
        - bash: cmake -Bbuild
          displayName: CMake configure
          
        - bash: cmake --build build --config Release --parallel 4
          displayName: CMake Build
